baseURL = "http://example.org/"
languageCode = "en-us"
title = "Blog personal óscar"
theme = "ananke"

#menu

[[menu.main]]
name = "Información"
url = "/pri/primera.md"
weight = 3

[[menu.main]]
name = "contacto"
url = "/pri/contacto.md"
weight = 3

